### ISSUE TITLE
day08 - AlertDialog 재사용시 또는 사용 후 Toast 메시지 호출시 The specified child already has a parent. You must call removeView() on the child's parent first. EXCEPTION

### ISSUE THREAD

**Issue by pby2017** [pby2017/study-android-basic-itbank#13]
> 버튼 클릭 이벤트 내 정의된 문제를 일으키는 코드  
> 1회 정상 호출 후 2회 호출 시 문제 발생
```java
AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(MyDialogActivity.this);
alertDialogBuilder.setTitle("제목");
alertDialogBuilder.setIcon(R.mipmap.ic_launcher);
alertDialogBuilder.setView(viewDialog);

alertDialogBuilder.setPositiveButton("확인", new DialogInterface.OnClickListener() {
    @Override
    public void onClick(DialogInterface dialog, int which) {

        editTextName.setText(editTextDialogName.getText().toString());
        editTextEmail.setText(editTextDialogEmail.getText().toString());

        Toast.makeText(getApplicationContext(), "확인을 누르셨어요.", Toast.LENGTH_SHORT).show();
    }
});

alertDialogBuilder.setNegativeButton("취소", new DialogInterface.OnClickListener() {
    @Override
    public void onClick(DialogInterface dialog, int which) {
        Toast.makeText(getApplicationContext(), "취소를 누르셨어요.", Toast.LENGTH_SHORT).show();
    }
});

alertDialogBuilder.show();
break;
```

**Comment by pby2017** [comment]
아래 코드 실행 여부에 따라 위의 Exception 발생 여부가 결정됨.
```java
alertDialogBuilder.setView(viewDialog);

// Test code
if (viewDialog.getParent() == null) {
    alertDialogBuilder.setView(viewDialog);
}
```

**Comment by pby2017** [comment]
> ParentView 는 FrameLayout이었음.
```java
viewDialog.getParent() // FrameLayout
```
> ParentView에서 removeView 호출하는 코드 추가
```java
if (viewDialog.getParent() != null) {
    ((ViewGroup) viewDialog.getParent()).removeView(viewDialog);
}
```

**Comment by bonchangkoo** [comment]
> 아래 코드 실행 여부에 따라 위의 Exception 발생 여부가 결정됨.
> 
> ```java
> alertDialogBuilder.setView(viewDialog);
> 
> // Test code
> if (viewDialog.getParent() == null) {
>     alertDialogBuilder.setView(viewDialog);
> }
> ```

제가 병용님 코드로 재현해봤는데 해당 코드 없어도 강제종료 안되네요.

**Comment by bonchangkoo** [comment]
그리고 금요일에 말씀드린 dismiss 처리는 잘못말씀드린거같아요;;ㅋㅋ

**Comment by pby2017** [comment]
> > 아래 코드 실행 여부에 따라 위의 Exception 발생 여부가 결정됨.
> > ```java
> > alertDialogBuilder.setView(viewDialog);
> > 
> > // Test code
> > if (viewDialog.getParent() == null) {
> >     alertDialogBuilder.setView(viewDialog);
> > }
> > ```
> 
> 제가 병용님 코드로 재현해봤는데 해당 코드 없어도 강제종료 안되네요.

앗 이슈 답변을 이제 확인했습니다. 답변 달아주셨었군요. 감사합니다!~~

그럼 참조해주신 코드의 Test code 부분은 없어도 실행하는 데 문제는 없고,
가장 최근에 제가 이슈에 등록한 아래 코드는 있어야 하는 코드 맞지요??
> ```java
> if (viewDialog.getParent() != null) {
>     ((ViewGroup) viewDialog.getParent()).removeView(viewDialog);
> }
> ```
위 코드를 추가하기 전에는 문제가 발생했었는데
추가한 뒤로는 문제가 발생하지 않았습니다 ~!

[문제를 일으켰던 파일 : day08 - example01 - MyDialogActivity.java](https://github.com/pby2017/study-android-basic-itbank/blob/master/day08/app/src/main/java/com/example/day08/example01/MyDialogActivity.java)

**Comment by pby2017** [comment]
> 그리고 금요일에 말씀드린 dismiss 처리는 잘못말씀드린거같아요;;ㅋㅋ

아, dismiss 도 조사하면서
dialog 관련해서
dismiss, cancel 메소드가 호출된다는 것을 알게 되었습니다 ㅎㅎ.

**Comment by pby2017** [comment]
# @bonchangkoo 님 수정 코드
> 주석 처리는 제거된 코드임  
> removeView(View) 호출 코드 삭제 가능
## 클래스 멤버 변수 수정
* Activity에 존재하는 View가 아니면 제거
* Builder 제거
```java
// private View myDialogView;
// private AlertDialog.Builder
->
private AlertDialog dialog;
```

## initView() 메소드 수정
* Activity의 View에 대한 초기화가 아니면 제거
```java
private void initView() {
    ...
    // dialog에 존재하는 View 초기화 코드
    // dialogNameEditText = myDialogView.findViewById(R.id.edit_text_dialog_name);
    // dialogEmailEditText = myDialogView.findViewById(R.id.edit_text_dialog_email);
}
```

## 클릭 이벤트에 실행되는 dialog 조건문 수정
* builder는 숨김
* dialog.show() 만 할 수 있게 함
```java
// if (alertDialogBuilder == null) {
    // buildAlertDialog();
->
if (dialog == null) {
    dialog = buildAlertDialog();
}

// 없어도 오류 발생 안함
// if (myDialogView.getParent() != null) {
//     ((ViewGroup) myDialogView.getParent()).removeView(myDialogView);
// }

// alertDialogBuilder.show();
->
dialog.show();
```

## buildAlertDialog 반환형 수정
* dialog build 결과를 반환함
```java
// private void buildAlertDialog() {
->
private AlertDialog buildAlertDialog() {
    ...
    //
    return alertDialogBuilder.create();
}
```
